name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write  # This allows GITHUB_TOKEN to create releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.22'

      - name: Check node version
        run: node -v

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Configure git for pushing to dist branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push dist folder to dist branch
        run: |
          git fetch origin
          git checkout dist
          git add -f dist
          git commit -m "chore: update dist folder" || echo "No changes to commit"
          git push origin dist --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}